"use strict";

const FRONTEND_TEST_IDS = Object.freeze({
  rentCreateOrderCta: "rent-create-order-cta",
  rentPaymentInstructions: "rent-payment-instructions",
  rentOrderId: "rent-order-id",
  rentOrderStatus: "rent-order-status",
  rentRefreshStatus: "rent-refresh-status",
  rentWalletPaymentCta: "rent-wallet-payment-cta",
  rentWalletPaymentTxid: "rent-wallet-payment-txid",
  rentPaymentMethodWallet: "rent-payment-method-wallet",
  rentPaymentMethodDeposit: "rent-payment-method-deposit",
  rentPaymentAmount: "rent-payment-amount",
  rentPaymentAddress: "rent-payment-address",
  rentPaymentReference: "rent-payment-reference",
  rentPollingError: "rent-polling-error",
  exchangeCreateOrderCta: "exchange-create-order-cta",
  exchangeDepositInstructions: "exchange-deposit-instructions",
  exchangeOrderId: "exchange-order-id",
  exchangeOrderStatus: "exchange-order-status",
  exchangeRefreshStatus: "exchange-refresh-status",
  exchangeWalletDepositCta: "exchange-wallet-deposit-cta",
  exchangeWalletDepositTxid: "exchange-wallet-deposit-txid",
  exchangePaymentAmount: "exchange-payment-amount",
  exchangePaymentAddress: "exchange-payment-address",
  exchangePaymentReference: "exchange-payment-reference",
  exchangePaymentContract: "exchange-payment-contract",
  exchangePollingError: "exchange-polling-error",
  opsTokenInput: "ops-token-input",
  opsLoadStatus: "ops-load-status",
  opsMode: "ops-mode",
  opsReadyForLive: "ops-ready-for-live",
  opsWarnings: "ops-warnings",
  opsBacklogSummary: "ops-backlog-summary",
  opsConfirmActions: "ops-confirm-actions",
  opsScanDeposits: "ops-scan-deposits",
  opsDrainProvider: "ops-drain-provider",
  opsDrainExchange: "ops-drain-exchange",
  opsActionResult: "ops-action-result",
  opsError: "ops-error",
});

module.exports = {
  FRONTEND_TEST_IDS,
};
